// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flthurtynasbngfubsye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsdGh1cnR5bmFzYm5nZnVic3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwOTQ2MjUsImV4cCI6MjA1NzY3MDYyNX0.tnfmXJwi6s5nfowg6BY0gQlCa_KGgkCQwji5X7fZKTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);